### ISSUE TITLE
Layout download fails when detailsV2 is None

### ISSUE THREAD

**Issue by maxgubler** [demisto/demisto-sdk#2599]
When downloading a layout with its json value of detailsV2 `null`, an error occurs:
`'NoneType' object has no attribute 'get'`

This bug appears to have been introduced with 0bdf53c (@merit-maita).
https://github.com/demisto/demisto-sdk/blob/0bdf53c0979047d801aebb560adb6a5b8ab05cb2/demisto_sdk/commands/download/downloader.py#L257

When the detailsV2 json value is `null`, detailsV2 will be `None` in python. Using `file_json_object.get('detailsV2', {})` will return `None` (and not `{}` as intended).

**Comment by maxgubler** [comment]
Closed the fix #2600 since #2623 has been merged in.
